config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cours', to: "courses#index"
  get 'cours/:id', to: 'courses#show', as: 'cour'
  get "classe", to: 'grades#index'
  get "matiere", to: 'matters#index'
  root 'static_pages#home'
  get '/home', to: redirect('/')
  get '/accueil', to: redirect('/')
  get '/legale', to: 'static_pages#legal'
  get '/contact', to: redirect('/contacts')
  resources :contacts, only: [:index, :create ]
  
  authenticate :user do
    mount Avo::Engine => Avo.configuration.root_path
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :subject, validate: true
    attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,   validate: true
    attribute :files, attachment: true
    attribute :nickname,  captcha: true

    def headers
      {
        :subject => subject,
        :to => Rails.application.credentials.mail[:to],
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/course.rb
class Course < ApplicationRecord
  has_one_attached :illustration
  has_many_attached :courses
  has_many_attached :exercices
  has_many_attached :m_res
  belongs_to :grade
  belongs_to :matter
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_one_attached :illustration
  
  alias_attribute :classe_id, :id

  has_many :courses
  has_many :matter, through: :courses
end

app/models/matter.rb
class Matter < ApplicationRecord
  has_one_attached :illustration

  alias_attribute :matter_id, :id

  has_many :courses
  has_many :grade, through: :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avo/courses_controller.rb
class Avo::CoursesController < Avo::ResourcesController
end

app/controllers/avo/grades_controller.rb
class Avo::GradesController < Avo::ResourcesController
end

app/controllers/avo/matters_controller.rb
class Avo::MattersController < Avo::ResourcesController
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
        @contact = Contact.new
    end
  
    def create
        @contact = Contact.new(contact_params)
        @contact.request = request
        if @contact.deliver
          flash.now[:success] = 'Votre message a bien été envoyé !'
          @contact = Contact.new
        elsif !@contact.valid?
          flash.now[:error] = "Des erreurs dans le formulaire on été détectés : #{@contact.errors.full_messages.to_sentence}"
        else
          flash.now[:error] = "Votre message n'a pas pu être envoyé !"
        end
        render :index
    end

    private 
        def contact_params
            params.require(:contact).permit(:name, :subject, :email, :message, :nickname, files: [])
        end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.where(grade_id: params[:classe_id], matter_id: params[:matter_id]);
    
    begin
      @matter = Matter.find(params[:matter_id])
    rescue ActiveRecord::RecordNotFound
      params.delete :matter_id
      return redirect_to matiere_path(query_params_permit)
    end

    begin
      @classe = Grade.find(params[:classe_id])
      puts @classe
    rescue ActiveRecord::RecordNotFound
      params.delete :classe_id
      return redirect_to classe_path(query_params_permit)
    end
  end

  def show
    @course = Course.find(params[:id])
    @classe = @course.grade
    @matter = @course.matter
  end

  private 
    def query_params_permit
      params.permit(:matter_id, :classe_id)
    end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index    
    @classes = Grade.all
    @matter = params[:matter_id].present? ? Matter.find(params[:matter_id]) : nil
    rescue ActiveRecord::RecordNotFound
      params.delete :matter_id
      redirect_to request.path, :params => params
    @classes
  end

  private 

    def matter_params
      params.require(:matter).permit(:matter_id)
    end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  def index    
    @matters = Matter.order('id ASC').all
    @classe = params[:classe_id].present? ? Grade.find(params[:classe_id]) : nil
    rescue ActiveRecord::RecordNotFound
      params.delete :classe_id
      redirect_to request.path, :params => params
    @matters
  end

  private 

    def matters_params
      params.require(:grade).permit(:classe_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @matters = Matter.order('id ASC').all
  end

  def legal
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def create_title(str)
        cons_str = "MatPhyLab : Votre nouvelle façon de suivre les cours"
        if str.nil? || str.empty?
            cons_str
        else
            "#{str} | #{cons_str}"
        end
    end

    def create_url(classe_id, matter_id)
        if !classe_id.nil? && !matter_id.nil?
            cours_path(params.merge({:classe_id => classe_id, :matter_id => matter_id}).permit(:matter_id, :classe_id))
        elsif classe_id.nil? && !matter_id.nil?
            classe_path(params.merge({:matter_id => matter_id}).permit(:matter_id, :classe_id))
        elsif !classe_id.nil? && matter_id.nil?
            matiere_path(params.merge({:classe_id => classe_id}).permit(:matter_id, :classe_id))
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

    def get_number_of_skills(course)
        course.skills.count
    end

    def get_number_of_cours(course)
        course.courses.count
    end

    def get_number_of_exercices(course)
        course.exercices.count
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/matter_helper.rb
module MatterHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/index.html.erb
<div class="contact-page">
    <h1>Une question ? un problèmes dans les cours ?</h1>
    <p>Contact ton professeur</p>
    <div class="login">
  <div class="logo-container">
    <%= image_tag "book.svg", class: "book-logo", alt: "logo" %>
  </div>

  <div class="login-form-container">
      <div class="title-container">
        <h3>Contact ton professeur !</h3>
        <p>Pour toutes tes questions ta professeure est la</p>
      </div>
    <%= form_with model: @contact do |f| %>
        <div class="field">
            <%= f.text_field :name, autofocus: true, autocomplete: "username", placeholder: "Entrez votre Nom et prénom" %>
        </div>

        <div class="field">
            <%= f.text_field :subject, autofocus: true, placeholder: "Entrez le sujet de votre mail" %>
        </div>

        <div class="field">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Entrez votre email" %>
        </div>

        <div class="field textarea">
            <%= f.text_area :message, placeholder: "Entrez votre message" %>
        </div>

        <div class="field pj">
            <%= f.label :files, "Piece jointes" %>
            <%= f.file_field :files, multiple: true, accept: ".pdf,.doc" %>
        </div>


        <div class="field hidden">
            <%= f.text_field :nickname %>
        </div>

        <div class="actions">
            <%= f.submit "Envoyer le mail" %>
        </div>
    <% end %>

  </div>
</div>
</div>

app/views/courses/_course.html.erb
<%= link_to cour_path(course), :class => "cour" do %>
    <div class="cour-illus">
        <%= image_tag course.illustration, alt: course.illustration.blob.filename %>
    </div>
    <div class="cour-text">
        <p class="title"><%= course.title %></p>
        <div class="compt-container col-1">
            <div class="round"></div>
            <p><%= get_number_of_skills course %> Compétences</p>
        </div>
        <div class="compt-container col-2">
            <div class="round"></div>
            <p><%= get_number_of_cours course %> Cours</p>
        </div>
        <div class="compt-container col-3">
            <div class="round"></div>
            <p><%= get_number_of_exercices course %> Exercices</p>
        </div>
    </div>
<% end %>

app/views/courses/index.html.erb
<% provide(:title, "Cours") %>


<div class="cours-page">

<% if !@matter.nil? %>
    <div class="curr-grade">
    <%= image_tag @matter.illustration, class: "curr-grade-illustration" %>
    <p><%= link_to @matter.title, matiere_path(:classe_id => @classe.id) %></p>
    </div>
<% end %>

<% if !@classe.nil? %>
    <div class="curr-classe">
    <%= image_tag @classe.illustration, class: "curr-class-illustration" %>
    <p><%= link_to @classe.title, classe_path(:matter_id => @matter.id) %></p>
    </div>
<% end %>


<% if @courses.nil? || @courses.empty? %>

    <p class="nf">Aucun cours n'est encore disponible pour la matiere <%= @matter.title %> et la classe <%= @classe.title %></p>
    <p class="rt"><%= link_to "Retournez a l'accueil ?", root_path %></p>
<% else %>

<div class="cours">
<%= render @courses %>
</div>    
<% end %>

</div>

app/views/courses/show.html.erb
<% provide(:title, @course.title) %>

<div class="cours-page show">

<% if !@matter.nil? %>
    <div class="curr-grade">
    <%= image_tag @matter.illustration, class: "curr-grade-illustration" %>
    <p><%= link_to @matter.title, matiere_path(:classe_id => @classe.id) %></p>
    </div>
<% end %>

<% if !@classe.nil? %>
    <div class="curr-classe">
    <%= image_tag @classe.illustration, class: "curr-class-illustration" %>
    <p><%= link_to @classe.title, classe_path(:matter_id => @matter.id) %></p>
    </div>
<% end %>

<div class="retur">
    <%= link_to cours_path(:matter_id => @matter.id, :classe_id => @classe.id) do %>
    <%= image_tag "back.png" %>
    <p>Retour a la liste des cours</p>
    <% end %>
</div>

<div class="content">
    <div class="illustration">
        <%= image_tag @course.illustration, alt: @course.illustration.blob.filename %>
    </div>

    <div class="title-cont">
        <p><%= @course.title %></p>
    </div>

    <div class="comp-cont">
        <div class='t'>
        <h3>Compétences</h3>
        </div>
        <ul>
        <% @course.skills.each do |k,v| %>
            <li><%= v %></li>
        <% end %>
        </ul>
    </div>

    <div class="ress-cont">
        <div class='t'>
            <h3>Ressources</h3>
        </div>

        <% if !@course.courses.nil? && !@course.courses.empty? %>
        <div class="cour-pdf">
            <h4>Cours</h4>
            <ul>
                <% @course.courses.each do |f| %>
                    <li><%= image_tag "docs.png"%><p><%= f.blob.filename %></p><%= link_to rails_blob_path(f.blob, disposition: 'attachment')  do %>
                        <%= image_tag "Download.png", alt: 'Telechargez le fichier', class: "ddl-img" %>
                    <% end %> </li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <% if !@course.exercices.nil? && !@course.exercices.empty? %>
        <div class="exo-pdf">
            <h4>Exercices</h4>
            <ul>
                <% @course.exercices.each do |f| %>
                    <li><%= image_tag "docs.png"%><p><%= f.blob.filename %></p><%= link_to rails_blob_path(f.blob, disposition: 'attachment')  do %>
                        <%= image_tag "Download.png", alt: 'Telechargez le fichier', class: "ddl-img" %>
                    <% end %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <% if !@course.m_res.nil? && !@course.m_res.empty? %>
        <div class="mrs-pdf">
            <h4>Autres Ressources</h4>
            <ul>
                <% @course.m_res.each do |f| %>
                    <li><%= image_tag "docs.png"%><p><%= f.blob.filename %></p><%= link_to rails_blob_path(f.blob, disposition: 'attachment') do %>
                        <%= image_tag "Download.png", alt: 'Telechargez le fichier', class: "ddl-img" %>
                    <% end %> </li>
                <% end %>
            </ul>
        </div>
        <% end %>
    </div>

    <div class="contact-cont">
        <div class='t'>
        <h3>Contact</h3>
        </div>
        <p>Tu as des difficultés ? Des problèmes avec les fichiers ?</p>
        <p><%= link_to "Contact ton professeur", contacts_path %></p>
    </div>
</div>
</div>

app/views/grades/_grade.html.erb
<%= link_to create_url(grade.id, params[:matter_id]), :class =>"grade" do %>
    <%= image_tag grade.illustration, class: 'img-illus-grade' %>
    <p class="grade-title"><%= grade.title %></p>
<% end %>

app/views/grades/index.html.erb
<% provide(:title, "Classes") %>

<div class="classe-page">

<% if !@matter.nil? %>
    <div class="curr-grade">
    <%= image_tag @matter.illustration, class: "curr-grade-illustration" %>
    <p><%= link_to @matter.title, matiere_path %></p>
    </div>
<% end %>

<h1>Choissis une classe</h1>

<div class="classes">
    <%= render @classes%>
</div>

</div>

app/views/matters/_matter.html.erb
<%= link_to create_url(params[:classe_id], matter.id), :class => "matter" do %>
    <%= image_tag matter.illustration, class: 'img-illus-matter' %>
    <p class="matter-title"><%= matter.title %></p>
<% end %>

app/views/matters/index.html.erb
<% provide(:title, "Matières") %>

<div class="matter-page">
<% if !@classe.nil? %>
    <div class="curr-classe">
    <%= image_tag @classe.illustration, class: "curr-class-illustration" %>
    <p><%= link_to @classe.title, classe_path %></p>
    </div>
<% end %>

<h1>Choissis une matière</h1>
<div class="matters">
    <%= render @matters%>
</div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Accueil") %>

<div class="home">
    <div class="accueil">
        <h1>Bienvenue sur Matphylab</h1>
        <p>Votre nouvelle maniere de suivre les cours</p>
    </div>

    <p class="choose">Choisis un cours ci-dessous :</p>
    <div class="matters">
        <%= render @matters %>
    </div>
</div>