config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'cours', to: "courses#index"
  get 'cours/:id', to: 'courses#show', as: 'cour'
  get "classe", to: 'grades#index'
  get "matiere", to: 'matters#index'
  root 'static_pages#home'
  get '/home', to: redirect('/')
  get '/accueil', to: redirect('/')
  get '/legale', to: 'static_pages#legal'
  get '/contact', to: redirect('/contacts')
  resources :contacts, only: [:index, :create ]
  
  authenticate :user do
    mount Avo::Engine => Avo.configuration.root_path
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name, validate: true
    attribute :subject, validate: true
    attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :message,   validate: true
    attribute :files, attachment: true
    attribute :nickname,  captcha: true

    def headers
      {
        :subject => subject,
        :to => Rails.application.credentials.mail[:to],
        :from => %("#{name}" <#{email}>)
      }
    end
end

app/models/course.rb
class Course < ApplicationRecord
  has_one_attached :illustration
  has_many_attached :courses
  has_many_attached :exercices
  has_many_attached :m_res
  belongs_to :grade
  belongs_to :matter
end

app/models/grade.rb
class Grade < ApplicationRecord
  has_one_attached :illustration
  
  alias_attribute :classe_id, :id

  has_many :courses
  has_many :matter, through: :courses
end

app/models/matter.rb
class Matter < ApplicationRecord
  has_one_attached :illustration

  alias_attribute :matter_id, :id

  has_many :courses
  has_many :grade, through: :courses
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avo/courses_controller.rb
class Avo::CoursesController < Avo::ResourcesController
end

app/controllers/avo/grades_controller.rb
class Avo::GradesController < Avo::ResourcesController
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def index
        @contact = Contact.new
    end
  
    def create
        @contact = Contact.new(contact_params)
        @contact.request = request
        if @contact.deliver
          flash.now[:success] = 'Votre message a bien été envoyé !'
          @contact = Contact.new
        elsif !@contact.valid?
          flash.now[:error] = "Des erreurs dans le formulaire on été détectés : #{@contact.errors.full_messages.to_sentence}"
        else
          flash.now[:error] = "Votre message n'a pas pu être envoyé !"
        end
        render :index
    end

    private 
        def contact_params
            params.require(:contact).permit(:name, :subject, :email, :message, :nickname, files: [])
        end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.where(grade_id: params[:classe_id], matter_id: params[:matter_id]);
    
    begin
      @matter = Matter.find(params[:matter_id])
    rescue ActiveRecord::RecordNotFound
      params.delete :matter_id
      return redirect_to matiere_path(query_params_permit)
    end

    begin
      @classe = Grade.find(params[:classe_id])
      puts @classe
    rescue ActiveRecord::RecordNotFound
      params.delete :classe_id
      return redirect_to classe_path(query_params_permit)
    end
  end

  def show
    @course = Course.find(params[:id])
    @classe = @course.grade
    @matter = @course.matter
  end

  private 
    def query_params_permit
      params.permit(:matter_id, :classe_id)
    end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index    
    @classes = Grade.all
    @matter = params[:matter_id].present? ? Matter.find(params[:matter_id]) : nil
    rescue ActiveRecord::RecordNotFound
      params.delete :matter_id
      redirect_to request.path, :params => params
    @classes
  end

  private 

    def matter_params
      params.require(:matter).permit(:matter_id)
    end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
  def index    
    @matters = Matter.order('id ASC').all
    @classe = params[:classe_id].present? ? Grade.find(params[:classe_id]) : nil
    rescue ActiveRecord::RecordNotFound
      params.delete :classe_id
      redirect_to request.path, :params => params
    @matters
  end

  private 

    def matters_params
      params.require(:grade).permit(:classe_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @matters = Matter.order('id ASC').all
  end

  def legal
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def create_title(str)
        cons_str = "MatPhyLab : Votre nouvelle façon de suivre les cours"
        if str.nil? || str.empty?
            cons_str
        else
            "#{str} | #{cons_str}"
        end
    end

    def create_url(classe_id, matter_id)
        if !classe_id.nil? && !matter_id.nil?
            cours_path(params.merge({:classe_id => classe_id, :matter_id => matter_id}).permit(:matter_id, :classe_id))
        elsif classe_id.nil? && !matter_id.nil?
            classe_path(params.merge({:matter_id => matter_id}).permit(:matter_id, :classe_id))
        elsif !classe_id.nil? && matter_id.nil?
            matiere_path(params.merge({:classe_id => classe_id}).permit(:matter_id, :classe_id))
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

    def get_number_of_skills(course)
        course.skills.count
    end

    def get_number_of_cours(course)
        course.courses.count
    end

    def get_number_of_exercices(course)
        course.exercices.count
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/matter_helper.rb
module MatterHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="f-row">
        <ul>
            <li><%= link_to "Légales", legale_path %></li>
            <li><%= link_to "Cookies", legale_path(anchor: "Cookies") %></li>
            <li><%= link_to "Contact", contacts_path %></li>
        </ul>
    </div>

    <div class="l-row">
        <p>Copyright &#169; <%= Date.current.year %> et <a href="https://iuristus.com" target="_blank">Iuristus 0</a>, <a href="https://boutvalentin.com" target="_blank">BOUT Valentin</a></p>
    </div>

    <%# <div class="relative-back">
        <%= image_tag 'w-form-footer.svg' %>
    <%# </div> %>
</footer>

app/views/layouts/_header.html.erb
<header id="header">
    <div class="always-on">

        <div class="left-part">
        <%= link_to root_path do %>
        <div class="header-img-container">
            <%= image_tag "book.svg", alt: "logo", class: "header-logo-img" %>
        </div>

        <p>Matphylab</p>
        </div>

        <% end %>

        <div class="icon-container">
            <%= image_tag "Hamburger.svg", alt: "logo", class: "icon-header-img", id: 'open' %>
            <%= image_tag "Close.svg", alt: "logo", class: "icon-header-img hidden", id: 'close' %>

        </div>
    </div>


        <div class="weird-form-top">
            <%= image_tag "w-form-header.svg", alt: '', class: 'weird-form-top-img' %>
        </div>

    <div class="big-header hidden" id="big-header">
        <nav>
            <ul>
                <li><%= link_to "Matières", matiere_path %>
                <% if current_page?(:controller => '/matters', :action => 'index') %>
                    <%= image_tag "Trait.svg", alt: '', class: 'trait' %>
                <% end %>
                </li>
                <li><%= link_to "Classes", classe_path %>
                <% if current_page?(:controller => '/grades', :action => 'index') %>
                    <%= image_tag "Trait.svg", alt: '', class: 'trait' %>
                <% end %>
                </li>
                <li><%= link_to "Contact", contacts_path %>
                <% if current_page?(:controller => '/contacts', :action => 'index') %>
                    <%= image_tag "Trait.svg", alt: '', class: 'trait' %>
                <% end %>
                </li>
                <li><%= link_to "Légales", legale_path %>
                <% if current_page?(:controller => '/static_pages', :action => 'legal') %>
                    <%= image_tag "Trait.svg", alt: '', class: 'trait' %>
                <% end %>
                </li>

            <ul>
        </nav>
    </div>
</header>

app/views/layouts/_ogtag.html.erb
<!-- Primary Meta Tags -->
<meta name="description" content="Matphylab est un site internet construit dans le but d'ameliorer les cours, nottament en distanciel, à travers l'utilisation d'une platforme commune entre élèves et enseignant">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://matphylab.herokuapp.com/">
<meta property="og:title" content="Matphylab : Votre nouvelle facon de suivre les cours">
<meta property="og:description" content="Matphylab est un site internet construit dans le but d'ameliorer les cours, nottament en distanciel, à travers l'utilisation d'une platforme commune entre élèves et enseignant">
<meta property="og:image" content="<%= image_path("book.png") %>">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content=https://matphylab.herokuapp.com/">
<meta property="twitter:title" content="Matphylab : Votre nouvelle facon de suivre les cours">
<meta property="twitter:description" content="Matphylab est un site internet construit dans le but d'ameliorer les cours, nottament en distanciel, à travers l'utilisation d'une platforme commune entre élèves et enseignant">
<meta property="twitter:image" content="<%= image_path("book.png") %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= create_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/ogtag' %>
    
    <meta name="turbolinks-cache-control" content="no-cache"> 

    <link rel="icon" href="<%= image_path('book.png') %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% flash.each do |key, message| %>
      <p class="alert alert-<%= key %>"><%= message %></p>
    <% end %>
    <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>